name: sooqyria
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: 4.7.2
  intl: ^0.19.0
  flutter_screenutil: ^5.9.3
  flutter_inappwebview: ^6.1.5
  get_storage: ^2.1.1
  r_dotted_line_border: ^0.1.1
  carousel_slider: ^5.0.0
  cached_network_image:
  image_picker: 1.1.2
  logger: ^2.4.0
  lottie: any
  iconsax: ^0.0.8
  restart_app: ^1.3.2
  flutter_animate: ^4.3.0
  loading_animation_widget: ^1.2.0
  pin_code_fields: ^8.0.0
  dropdown_button2: ^2.3.9
  flutter_svg: ^2.2.0
  flutter_otp_text_field: ^1.5.1+1
  flutter_dash: ^1.0.0
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  share_plus: ^11.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0



flutter:


  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/Double Check.svg
    - assets/icons/acs.png
    - assets/icons/call icon.png
    - assets/icons/global.png
    - assets/icons/goarrow.png
    - assets/icons/home.svg
    - assets/icons/inboxNav.svg
    - assets/icons/menu.svg
    - assets/icons/menuNav.svg
    - assets/icons/message.svg
    - assets/icons/police.png
    - assets/icons/pp.png
    - assets/icons/ss.png
    - assets/images/
    - assets/images/bag 1.png
    - assets/images/car.png
    - assets/images/car2.png
    - assets/images/home 1.png
    - assets/images/job.png
    - assets/images/map.png
    - assets/images/pawprint 1.png
    - assets/images/service.png
    - assets/images/state.png
    - assets/logo/


