// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'sooqyria';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String DOUBLE_CHECK = 'assets/icons/Double Check.svg';
  static const String ICON = 'assets/icons/Icon.svg';
  static const String VECTOR = 'assets/icons/Vector.svg';
  static const String BAG_1 = 'assets/images/bag 1.png';
  static const String CAR = 'assets/images/car.png';
  static const String CAR2 = 'assets/images/car2.png';
  static const String HOME_1 = 'assets/images/home 1.png';
  static const String JOB = 'assets/images/job.png';
  static const String PAWPRINT_1 = 'assets/images/pawprint 1.png';
  static const String SERVICE = 'assets/images/service.png';
}
