// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'sooqyria';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String SUCCESS = 'assets/icons/success.svg';
  static const String APPLE = 'assets/logo/Apple.png';
  static const String APPTEXT = 'assets/logo/apptext.png';
  static const String FB = 'assets/logo/fb.png';
  static const String GOOGLE = 'assets/logo/google.png';
  static const String LOGO = 'assets/logo/logo.png';
  static const String ONBOARD_LOGO = 'assets/logo/onboard_logo.png';
}
