
import 'package:get/get_navigation/src/routes/get_route.dart';
import 'package:get/get_navigation/src/routes/transitions_type.dart';
import 'package:sooqyria/bindings/otp_binding.dart';
import 'package:sooqyria/bindings/register_second_binding.dart';
import 'package:sooqyria/bindings/reset_password_binding.dart';
import 'package:sooqyria/views/auth/otp_screen/screen/otp_screen.dart';
import 'package:sooqyria/views/auth/register/screen/register_screen.dart';
import 'package:sooqyria/views/auth/register_second_screen/screen/register_second_screen.dart';
import 'package:sooqyria/views/auth/reset_password/screen/reset_password_screen.dart';
import 'package:sooqyria/views/auth/reset_password_otp_screen/screen/reset_password_otp_screen.dart';

import '../bindings/Menus_binding.dart';
import '../bindings/aaccount_details_binding.dart';
import '../bindings/account_settings_binding.dart';
import '../bindings/add_category_type_binding.dart';
import '../bindings/add_place_from_binding.dart';
import '../bindings/address_binding.dart';
import '../bindings/all_car_list_binding.dart';
import '../bindings/animals_binding.dart';
import '../bindings/car_categories_binding.dart';
import '../bindings/car_overview_binding.dart';
import '../bindings/car_sub_category_binding.dart';
import '../bindings/categories_details_binding.dart';
import '../bindings/chat_binding.dart';
import '../bindings/favorite_binding.dart';
import '../bindings/favorite_overview_binding.dart';
import '../bindings/favorited_items_binding.dart';
import '../bindings/home_binding.dart';
import '../bindings/housing_overview_binding.dart';
import '../bindings/inbox_binding.dart';
import '../bindings/job_offers_category_binding.dart';
import '../bindings/login_binding.dart';
import '../bindings/my_adds_binding.dart';
import '../bindings/my_serches_binding.dart';
import '../bindings/navigation_binding.dart';
import '../bindings/new_and_used_product_binding.dart';
import '../bindings/notification_binding.dart';
import '../bindings/onboard_binding.dart';
import '../bindings/profile_section_binding.dart';
import '../bindings/real_state_category_binding.dart';
import '../bindings/real_state_housing_binding.dart';
import '../bindings/register_binding.dart';
import '../bindings/reset_password_otp_binding.dart';
import '../bindings/select_city_binding.dart';
import '../bindings/selection_category_binding.dart';
import '../bindings/seller_profile_binding.dart';
import '../bindings/services_binding.dart';
import '../bindings/set_password_binding.dart';
import '../bindings/splash_binding.dart';
import '../bindings/sub_category_binding.dart';
import '../bindings/vehicles_category_binding.dart';
import '../views/Menus/screen/Menus_screen.dart';
import '../views/aaccount_details/screen/aaccount_details_screen.dart';
import '../views/account_settings/screen/account_settings_screen.dart';
import '../views/add_category_type/screen/add_category_type_screen.dart';
import '../views/add_place_from/screen/add_place_from_screen.dart';
import '../views/address/screen/address_screen.dart';
import '../views/all_car_list/screen/all_car_list_screen.dart';
import '../views/animals/screen/animals_screen.dart';
import '../views/auth/login/screen/login_screen.dart';
import '../views/car_categories/screen/car_categories_screen.dart';
import '../views/car_overview/screen/car_overview_screen.dart';
import '../views/car_sub_category/screen/car_sub_category_screen.dart';
import '../views/categories_details/screen/categories_details_screen.dart';
import '../views/chat/screen/chat_screen.dart';
import '../views/favorite/screen/favorite_screen.dart';
import '../views/favorite_overview/screen/favorite_overview_screen.dart';
import '../views/favorited_items/screen/favorited_items_screen.dart';
import '../views/home/screen/home_screen.dart';
import '../views/housing_overview/screen/housing_overview_screen.dart';
import '../views/inbox/screen/inbox_screen.dart';
import '../views/job_offers_category/screen/job_offers_category_screen.dart';
import '../views/my_adds/screen/my_adds_screen.dart';
import '../views/my_serches/screen/my_serches_screen.dart';
import '../views/navigation/screen/navigation_screen.dart';
import '../views/new_and_used_product/screen/new_and_used_product_screen.dart';
import '../views/notification/screen/notification_screen.dart';
import '../views/onboard/screen/onboard_screen.dart';
import '../views/profile_section/screen/profile_section_screen.dart';
import '../views/real_state_category/screen/real_state_category_screen.dart';
import '../views/real_state_housing/screen/real_state_housing_screen.dart';
import '../views/select_city/screen/select_city_screen.dart';
import '../views/selection_category/screen/selection_category_screen.dart';
import '../views/seller_profile/screen/seller_profile_screen.dart';
import '../views/services/screen/services_screen.dart';
import '../views/set_password/screen/set_password_screen.dart';
import '../views/splash/screen/splash_screen.dart';
import '../views/sub_category/screen/sub_category_screen.dart';
import '../views/vehicles_category/screen/vehicles_category_screen.dart';
part '../routes/route_pages.dart';

class Routes {
  // Page List
  static var list = RoutePageList.list;

  // Route Names
  static const String splashScreen = '/splashScreen';
  static const String onboardScreen = '/onboardScreen';
  static const String loginScreen = '/loginScreen';
  static const String registerScreen = '/registerScreen';
  static const String registerSecondScreen = '/registerSecondScreen';
  static const String otpScreen = '/otpScreen';
  static const String forgotPasswordScreen = '/resetPasswordScreen';
  static const String forgotPasswordOtpScreen = '/resetPasswordOtpScreen';

  static const String set_passwordScreen = '/set_passwordScreen';
  static const String navigationScreen = '/navigationScreen';
  static const String homeScreen = '/homeScreen';
  static const String inboxScreen = '/inboxScreen';
  static const String MenusScreen = '/MenusScreen';
  static const String favoriteScreen = '/favoriteScreen';
  static const String real_stateScreen = '/real_stateScreen';
  static const String job_offersScreen = '/job_offersScreen';
  static const String new_and_used_productScreen = '/new_and_used_productScreen';
  static const String animalsScreen = '/animalsScreen';
  static const String servicesScreen = '/servicesScreen';
  static const String favorited_itemsScreen = '/favorited_itemsScreen';
  static const String favorite_overviewScreen = '/favorite_overviewScreen';
  static const String notificationScreen = '/notificationScreen';
  static const String chatScreen = '/chatScreen';
  static const String car_overviewScreen = '/car_overviewScreen';
  static const String seller_profileScreen = '/seller_profileScreen';
  static const String menuScreen = '/menuScreen';
  static const String categories_detailsScreen = '/categories_detailsScreen';
  static const String car_sub_categoryScreen = '/car_sub_categoryScreen';
  static const String sub_categoryScreen = '/sub_categoryScreen';
  static const String real_state_housingScreen = '/real_state_housingScreen';
  static const String housing_overviewScreen = '/housing_overviewScreen';
  static const String all_car_listScreen = '/all_car_listScreen';
  static const String car_categoriesScreen = '/car_categoriesScreen';
  static const String selselect_cityScreen = '/selselect_cityScreen';
  static const String select_cityScreen = '/select_cityScreen';
  static const String selection_categoryScreen = '/selection_categoryScreen';
  static const String add_category_typeScreen = '/add_category_typeScreen';
  static const String add_place_fromScreen = '/add_place_fromScreen';
  static const String my_addsScreen = '/my_addsScreen';
  static const String my_serchesScreen = '/my_serchesScreen';
  static const String profile_sectionScreen = '/profile_sectionScreen';
  static const String aaccount_detailsScreen = '/aaccount_detailsScreen';
  static const String addressScreen = '/addressScreen';
  static const String account_settingsScreen = '/account_settingsScreen';
  static const String real_state_categoryScreen = '/real_state_categoryScreen';
  static const String vehicles_categoryScreen = '/vehicles_categoryScreen';
  static const String job_offers_categoryScreen = '/job_offers_categoryScreen';
}
